### PR TITLE
updated flumeview-level to latest

### PR DESCRIPTION
**Pull request by luandro**
This is the last package used in `scuttlebot` that still uses old `Leveldown@1.7.2`, crashing on mobile.

### CODE REVIEW

**Comment by dominictarr** [comment]
aha, unfortunately this breaks the tests );
there are two different errors that I'm seeing.
one is
```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at join (path.js:1236:7)
    at module.exports (/home/dominic/c/secure-scuttlebutt/index.js:46:28)
    at Module.module.exports (/home/dominic/c/secure-scuttlebutt/test/add.js:19:27)
    at Object.<anonymous> (/home/dominic/c/secure-scuttlebutt/test/add.js:114:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```
that is because level@3 removed the `db.location` property which we were using...

the other one is 
```EncodingError: no decoder for:"\u0000"
    at /home/dominic/c/secure-scuttlebutt/node_modules/encoding-down/index.js:112:17
    at /home/dominic/c/secure-scuttlebutt/node_modules/level/node_modules/abstract-leveldown/abstract-iterator.js:29:14
    at /home/dominic/c/secure-scuttlebutt/node_modules/level/node_modules/leveldown/iterator.js:43:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

that's the key used for metadata in flumeview-level....

**Comment by dominictarr** [comment]
oh btw, secure-scuttlebutt is a module so it doesn't have a package-lock

**Comment by luandro** [comment]
:(

No can do?

**Comment by dominictarr** [comment]
I fixed it! merged into 18.0.2

**Comment by dominictarr** [comment]
i mean, 18.0.4

**Comment by luandro** [comment]
Awesome, thanks!

**Pull request merged**
