### PR TITLE
refactor createFeed out

### PR DESCRIPTION
**Pull request by dominictarr**
as discussed here: https://github.com/ssbc/ssb-keys/pull/12

### CODE REVIEW

**Comment by dominictarr** [comment]
this is backwards compatible, btw.

**Comment by pfraze** [comment]
ok looks good

**Comment by dominictarr** [comment]
alright, merging.

**Comment by dominictarr** [comment]
merged into secure-scuttlebutt@10.0.0 this was a breaking change since ssb-client depended on secure-scuttlebutt/feed which is now deleted. will make a pr to ssb client to update.

**Pull request merged**
