### PR TITLE
tracking pull request: mynosql

### PR DESCRIPTION
**Pull request by dominictarr**
use generic queries instead of hardcoded.
There is more work to do here, so won't be merging this just yet.

### CODE REVIEW

**Comment by dominictarr** [comment]
hey can we merge this? mynosql is pretty good now... and I need this for my talk in a few days.

**Comment by pfraze** [comment]
ok I just spent some time looking at mynosql and how you use it in bittodo. it is looking good!

could it work without being integrated into ssb? eg in bittodo could you do `nomysql(rpc.ssb)`?

**Comment by dominictarr** [comment]
@pfraze hmm, bittodo doesn't actually touch the db directly, it uses the client protocol.
that would work if bittodo had it's own server. (if we went down that road)

**Comment by dominictarr** [comment]
merged into 10.1.0

**Pull request merged**
