### PR TITLE
Add list of other projects in the same space.

### PR DESCRIPTION
**Pull request by ootoovak**
I have always liked the community vibe when projects list other projects in the same space. It is a way of saying this idea is important/interesting enough that other people are also working on solutions. We like our solution but we acknowledge there are others out there doing great work also. 👍😀

### CODE REVIEW

**Comment by dominictarr** [comment]
+1 also ipfs and firestar

**Comment by ahdinosaur** [comment]
:+1:. also [fosp](https://github.com/maufl/fosp-specification).

**Comment by ahdinosaur** [comment]
[slick](https://github.com/slick-io/slick)

**Comment by ootoovak** [comment]
I believe this is listed elsewhere in SSB community documentation so closing here.

**Pull request closed without merging**
