### PR TITLE
Bring level up-to-date

### PR DESCRIPTION
**Pull request by christianbundy**
Sorry for the never-ending PRs.

This (like the others) is meant to circumvent https://github.com/Level/leveldown/issues/455 by upgrading `level` to the most recent version. It passes `npm test`, but skepticism is warranted.

Thanks for putting up with me! :wink:

### CODE REVIEW

**Comment by myf** [comment]
level-test also needs to be updated eventhough it's a dev dependency. building secure-scuttlebutt itself will break it

**Comment by vweevers** [comment]
Do your tests cover usage of `level-sublevel`? Curious to know if that's compatible with latest level.

**Comment by christianbundy** [comment]
@vweevers Negative. I'm not very familiar with any of the Level components, so any/all expertise is very appreciated.

**Comment by christianbundy** [comment]
Looks like this waas taken care of in 78de3f624dd7718d606b66e95c1de35edd01327e, thanks!

**Pull request closed without merging**
