### PR TITLE
User stream

### PR DESCRIPTION
**Pull request by dominictarr**
read a single user's stream in any range or order.

### CODE REVIEW

**Comment by pfraze** [comment]
So why do we have a separate `createHistoryStream` from this? Couldnt we update `createHistoryStream` to work like this, and change the replicate plugin?

**Comment by dominictarr** [comment]
Security. This is more flexible than a replication needs, so we'd want to limit the way that a replicator can use it, and it's simplest to do that via a separate method until we have arg permissions (if ever)

**Comment by pfraze** [comment]
Ok makes sense, good to merge

**Comment by pfraze** [comment]
published `11.2.0`

**Pull request merged**
