### PR TITLE
update to new link convention (bump ssb-msgs to 3.0.0, update tests)

### PR DESCRIPTION
**Pull request by pfraze**
https://github.com/ssbc/secure-scuttlebutt/issues/94

### CODE REVIEW

**Comment by dominictarr** [comment]
hmm, you are gonna put a hyphen as the key? were we using replyTo on the old stuff?

**Comment by pfraze** [comment]
as discussed in another thread, I used `repliesTo` instead of `replies-to`

the `indexLinks` function from `ssb-msgs` gives the reltype in all lowercase, which means ssb will lowercase its indexes. I'm going to update the index fetch functions to do the same on its inputs. this should have the effect of making the reltype case-insensitive

**Comment by dominictarr** [comment]
Hmm, on second thoughts, this will actually create more complications elsewhere.
I think we are better off making things easy for ourselves at this point, rather than users.
If we did want to do something like this, we could enforce that keys are when added?
Or just allow case. What will this buy us?

**Comment by pfraze** [comment]
@dominictarr ok have a look at the index rebuild code in the last commit there

**Comment by pfraze** [comment]
@dominictarr updated `rebuildIndex`. I didnt go with the sync file because ssb isnt aware of the `~/.ssb` directory and it didnt seem very elegant to pass in a file path for storing metadata

**Comment by dominictarr** [comment]
good call.

okay merging this.

**Comment by dominictarr** [comment]
merged into 9.0.0

**Comment by dominictarr** [comment]
oops, didn't have all the commits.
One thing here is you are pushing your code to a branch on the ssbc repo - there is nothing wrong with this perse, but the git commands to merge this are more annoying (fetch, merge) rather than if you use another repo (pull)

**Comment by dominictarr** [comment]
this is fixed in 9.0.1

**Comment by pfraze** [comment]
@dominictarr i can use forks if you like. I do merges through github which papers over that annoyance

also, make sure you push the merged repo to github, this is still showing as unmerged

**Comment by dominictarr** [comment]
hmm, it's better to merge in the terminal so you can test. either way, using forks will still work with gh merge just the same.

**Pull request merged**
