### PR TITLE
more througher end-to-end tests

### PR DESCRIPTION
**Pull request by dominictarr**
also added a comment because I couldn't see where the decryption was when i reread the code.

### CODE REVIEW

**Comment by pfraze** [comment]
:cat2: :+1:

**Comment by dominictarr** [comment]
okay, this is now a minor change. keys are passed through the ./create module, which is used by scuttlebot, and i've tested this working with scuttlebot.

**Comment by dominictarr** [comment]
merging

**Comment by dominictarr** [comment]
merged into 13.1.1

**Pull request merged**
