### PR TITLE
oops, pass in the timestamp to the legacy migration

### PR DESCRIPTION
**Pull request by dominictarr**
@mmckegg this should do it

### CODE REVIEW

**Comment by mmckegg** [comment]
Oh, for some reason I thought old db was keyed by sequence? Is it timestamps? Awesome 🎉 

Guess I should have just tried it 😆

**Comment by dominictarr** [comment]
the old db is keyed by hash, but this is the _logDb_ but maybe it's confusing because that line is `pl.old(logDB, {...})`

**Comment by mmckegg** [comment]
Oh yes, of course 👍

**Comment by dominictarr** [comment]
merged into 16.3.7

**Pull request merged**
