### PR TITLE
standardizing getter output

### PR DESCRIPTION
**Pull request by pfraze**
see https://github.com/ssbc/secure-scuttlebutt/issues/76

started by adding `keys: true` support to `createFeedStream`. waiting on the rest till we have agreement

### CODE REVIEW

**Comment by pfraze** [comment]
@dominictarr ready for review

there were other places where the change could be made (eg `getLatest`) but i chose to leave that for now

**Comment by pfraze** [comment]
updates should be minimal. only added the `keys: true` opts to most. `add()` change was breaking

**Comment by pfraze** [comment]
oh, other breaking change - `createLogStream` no longer defaults to `keys: true` behavior, must be specified

**Comment by dominictarr** [comment]
discussion in irc:

``` 
<domanic> I'm guessing you made everything consistent, and that is why log stream is different now?
<domanic> also for these lines: https://github.com/ssbc/secure-scuttlebutt/pull/77/files#diff-168726dbe96b3ce427e7fedce31bb0bcR259
<domanic> it would be more consistent with the rest of secure-scuttlebutt style to use a ternary
<domanic> _keys ? {key, value} : value
<domanic> or at least, put the if else inside the cb to get, instead of duplicating the get
<pfraze> k. and yeah thats why log stream changed
<domanic> pfraze, maybe we should just make this consistent with levelup?
<pfraze> default it to true and add the value opt?
<domanic> https://github.com/rvagg/node-levelup/blob/master/lib/levelup.js#L403-L418
<domanic> I'm not sure whether we'd need the values: false
<pfraze> yeah, i'm good w/that
<domanic> but being consistent is good
<domanic> hmm...
<domanic> though, since these are indexes do we really need the key, would it be better to use the index key?
<domanic> I'm really not sure
<domanic> maybe the index could be on another property, like ts is on log stream?
<domanic> {values, keys, indexes} ?
<pfraze> yeah that could work, i just need the key attr
<domanic> hmm, we should probably leave that until we actually have a case... oh yeah, we do have a case because that is on log stream
<domanic> although, it doesn't give the entire key, just the significant part (in that case, the timestamp)
<pfraze> if we use gt/lt/gte/lte then the index attr would be useful
<domanic> yeah. we should use that, and also we should support live streams
<domanic> oh yeah, I added that to the link streams recently
<domanic> pfraze, hmm, maybe we are over thinking this? 
<domanic> maybe we should just tidy up the if else and merge?
```

**Comment by pfraze** [comment]
after sleeping on it i do feel like having `{keys:, values:}` behavior like in leveldb (where each can be by itself and they default to true) would be a good idea, because otherwise we're so similar. that would cause `createLogStream` to default behave as it did before, but `createFeedStream`, `createHistoryStream`, and `messagesLinkedToMessage` would change

it'll be a pain to change, but easier now than later?

**Comment by dominictarr** [comment]
okay if you wanna go that way I'm :+1:

**Comment by pfraze** [comment]
@dominictarr ok ready for review

**Comment by pfraze** [comment]
published `8.0.0`

**Pull request merged**
