### PR TITLE
don't crash on malformed message in add

### PR DESCRIPTION
**Pull request by dominictarr**
check if the added message is reasonable before attempting to validate. fixes
  https://github.com/ssbc/scuttlebot/issues/156

### CODE REVIEW

**Comment by noffle** [comment]
I'm getting a few breakages on this branch, FYI:

1. `mynosql` isn't in package.json
2. `isHash` is undefined in `validation.js` (meant `opts.isHash`?)
3. `opts` is undefined at index:js:293

**Comment by dominictarr** [comment]
oops

**Comment by dominictarr** [comment]
okay just merged https://github.com/ssbc/secure-scuttlebutt/pull/103 into this pull request which gets the other test passing.

**Comment by dominictarr** [comment]
merged #95 in too

**Comment by dominictarr** [comment]
merged into 10.1.0

**Pull request merged**
